/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as authenticatedClassifyRouteImport } from './routes/(authenticated)/classify'
import { Route as authenticatedBackendRouteRouteImport } from './routes/(authenticated)/backend/route'
import { Route as authenticatedJdsIndexRouteImport } from './routes/(authenticated)/jds.index'
import { Route as authenticatedBackendIndexRouteImport } from './routes/(authenticated)/backend/index'
import { Route as authenticatedJdsIdRouteImport } from './routes/(authenticated)/jds.$id'
import { Route as authenticatedClassSlugRouteImport } from './routes/(authenticated)/class.$slug'
import { Route as authenticatedBackendSettingsRouteImport } from './routes/(authenticated)/backend/settings'
import { Route as authenticatedBackendFitRouteImport } from './routes/(authenticated)/backend/fit'
import { Route as authenticatedBackendCorpusRouteImport } from './routes/(authenticated)/backend/corpus'
import { Route as authenticatedBackendAnalyticsRouteImport } from './routes/(authenticated)/backend/analytics'
import { Route as authenticatedClassSlugBuildRouteImport } from './routes/(authenticated)/class.$slug.build'
import { Route as authenticatedBackendStandardSlugRouteImport } from './routes/(authenticated)/backend/standard.$slug'
import { Route as authenticatedBackendJdsSlugRouteImport } from './routes/(authenticated)/backend/jds.$slug'
import { Route as authenticatedBackendEditSlugRouteImport } from './routes/(authenticated)/backend/edit.$slug'
import { Route as authenticatedBackendJdSlugSplatRouteImport } from './routes/(authenticated)/backend/jd.$slug.$'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedClassifyRoute = authenticatedClassifyRouteImport.update({
  id: '/classify',
  path: '/classify',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedBackendRouteRoute =
  authenticatedBackendRouteRouteImport.update({
    id: '/backend',
    path: '/backend',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedJdsIndexRoute = authenticatedJdsIndexRouteImport.update({
  id: '/jds/',
  path: '/jds/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedBackendIndexRoute =
  authenticatedBackendIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedBackendRouteRoute,
  } as any)
const authenticatedJdsIdRoute = authenticatedJdsIdRouteImport.update({
  id: '/jds/$id',
  path: '/jds/$id',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedClassSlugRoute = authenticatedClassSlugRouteImport.update({
  id: '/class/$slug',
  path: '/class/$slug',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedBackendSettingsRoute =
  authenticatedBackendSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedBackendRouteRoute,
  } as any)
const authenticatedBackendFitRoute = authenticatedBackendFitRouteImport.update({
  id: '/fit',
  path: '/fit',
  getParentRoute: () => authenticatedBackendRouteRoute,
} as any)
const authenticatedBackendCorpusRoute =
  authenticatedBackendCorpusRouteImport.update({
    id: '/corpus',
    path: '/corpus',
    getParentRoute: () => authenticatedBackendRouteRoute,
  } as any)
const authenticatedBackendAnalyticsRoute =
  authenticatedBackendAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => authenticatedBackendRouteRoute,
  } as any)
const authenticatedClassSlugBuildRoute =
  authenticatedClassSlugBuildRouteImport.update({
    id: '/build',
    path: '/build',
    getParentRoute: () => authenticatedClassSlugRoute,
  } as any)
const authenticatedBackendStandardSlugRoute =
  authenticatedBackendStandardSlugRouteImport.update({
    id: '/standard/$slug',
    path: '/standard/$slug',
    getParentRoute: () => authenticatedBackendRouteRoute,
  } as any)
const authenticatedBackendJdsSlugRoute =
  authenticatedBackendJdsSlugRouteImport.update({
    id: '/jds/$slug',
    path: '/jds/$slug',
    getParentRoute: () => authenticatedBackendRouteRoute,
  } as any)
const authenticatedBackendEditSlugRoute =
  authenticatedBackendEditSlugRouteImport.update({
    id: '/edit/$slug',
    path: '/edit/$slug',
    getParentRoute: () => authenticatedBackendRouteRoute,
  } as any)
const authenticatedBackendJdSlugSplatRoute =
  authenticatedBackendJdSlugSplatRouteImport.update({
    id: '/jd/$slug/$',
    path: '/jd/$slug/$',
    getParentRoute: () => authenticatedBackendRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/backend': typeof authenticatedBackendRouteRouteWithChildren
  '/classify': typeof authenticatedClassifyRoute
  '/': typeof authenticatedIndexRoute
  '/backend/analytics': typeof authenticatedBackendAnalyticsRoute
  '/backend/corpus': typeof authenticatedBackendCorpusRoute
  '/backend/fit': typeof authenticatedBackendFitRoute
  '/backend/settings': typeof authenticatedBackendSettingsRoute
  '/class/$slug': typeof authenticatedClassSlugRouteWithChildren
  '/jds/$id': typeof authenticatedJdsIdRoute
  '/backend/': typeof authenticatedBackendIndexRoute
  '/jds': typeof authenticatedJdsIndexRoute
  '/backend/edit/$slug': typeof authenticatedBackendEditSlugRoute
  '/backend/jds/$slug': typeof authenticatedBackendJdsSlugRoute
  '/backend/standard/$slug': typeof authenticatedBackendStandardSlugRoute
  '/class/$slug/build': typeof authenticatedClassSlugBuildRoute
  '/backend/jd/$slug/$': typeof authenticatedBackendJdSlugSplatRoute
}
export interface FileRoutesByTo {
  '/classify': typeof authenticatedClassifyRoute
  '/': typeof authenticatedIndexRoute
  '/backend/analytics': typeof authenticatedBackendAnalyticsRoute
  '/backend/corpus': typeof authenticatedBackendCorpusRoute
  '/backend/fit': typeof authenticatedBackendFitRoute
  '/backend/settings': typeof authenticatedBackendSettingsRoute
  '/class/$slug': typeof authenticatedClassSlugRouteWithChildren
  '/jds/$id': typeof authenticatedJdsIdRoute
  '/backend': typeof authenticatedBackendIndexRoute
  '/jds': typeof authenticatedJdsIndexRoute
  '/backend/edit/$slug': typeof authenticatedBackendEditSlugRoute
  '/backend/jds/$slug': typeof authenticatedBackendJdsSlugRoute
  '/backend/standard/$slug': typeof authenticatedBackendStandardSlugRoute
  '/class/$slug/build': typeof authenticatedClassSlugBuildRoute
  '/backend/jd/$slug/$': typeof authenticatedBackendJdSlugSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/backend': typeof authenticatedBackendRouteRouteWithChildren
  '/(authenticated)/classify': typeof authenticatedClassifyRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/(authenticated)/backend/analytics': typeof authenticatedBackendAnalyticsRoute
  '/(authenticated)/backend/corpus': typeof authenticatedBackendCorpusRoute
  '/(authenticated)/backend/fit': typeof authenticatedBackendFitRoute
  '/(authenticated)/backend/settings': typeof authenticatedBackendSettingsRoute
  '/(authenticated)/class/$slug': typeof authenticatedClassSlugRouteWithChildren
  '/(authenticated)/jds/$id': typeof authenticatedJdsIdRoute
  '/(authenticated)/backend/': typeof authenticatedBackendIndexRoute
  '/(authenticated)/jds/': typeof authenticatedJdsIndexRoute
  '/(authenticated)/backend/edit/$slug': typeof authenticatedBackendEditSlugRoute
  '/(authenticated)/backend/jds/$slug': typeof authenticatedBackendJdsSlugRoute
  '/(authenticated)/backend/standard/$slug': typeof authenticatedBackendStandardSlugRoute
  '/(authenticated)/class/$slug/build': typeof authenticatedClassSlugBuildRoute
  '/(authenticated)/backend/jd/$slug/$': typeof authenticatedBackendJdSlugSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/backend'
    | '/classify'
    | '/'
    | '/backend/analytics'
    | '/backend/corpus'
    | '/backend/fit'
    | '/backend/settings'
    | '/class/$slug'
    | '/jds/$id'
    | '/backend/'
    | '/jds'
    | '/backend/edit/$slug'
    | '/backend/jds/$slug'
    | '/backend/standard/$slug'
    | '/class/$slug/build'
    | '/backend/jd/$slug/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/classify'
    | '/'
    | '/backend/analytics'
    | '/backend/corpus'
    | '/backend/fit'
    | '/backend/settings'
    | '/class/$slug'
    | '/jds/$id'
    | '/backend'
    | '/jds'
    | '/backend/edit/$slug'
    | '/backend/jds/$slug'
    | '/backend/standard/$slug'
    | '/class/$slug/build'
    | '/backend/jd/$slug/$'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(authenticated)/backend'
    | '/(authenticated)/classify'
    | '/(authenticated)/'
    | '/(authenticated)/backend/analytics'
    | '/(authenticated)/backend/corpus'
    | '/(authenticated)/backend/fit'
    | '/(authenticated)/backend/settings'
    | '/(authenticated)/class/$slug'
    | '/(authenticated)/jds/$id'
    | '/(authenticated)/backend/'
    | '/(authenticated)/jds/'
    | '/(authenticated)/backend/edit/$slug'
    | '/(authenticated)/backend/jds/$slug'
    | '/(authenticated)/backend/standard/$slug'
    | '/(authenticated)/class/$slug/build'
    | '/(authenticated)/backend/jd/$slug/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/classify': {
      id: '/(authenticated)/classify'
      path: '/classify'
      fullPath: '/classify'
      preLoaderRoute: typeof authenticatedClassifyRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/backend': {
      id: '/(authenticated)/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof authenticatedBackendRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/jds/': {
      id: '/(authenticated)/jds/'
      path: '/jds'
      fullPath: '/jds'
      preLoaderRoute: typeof authenticatedJdsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/backend/': {
      id: '/(authenticated)/backend/'
      path: '/'
      fullPath: '/backend/'
      preLoaderRoute: typeof authenticatedBackendIndexRouteImport
      parentRoute: typeof authenticatedBackendRouteRoute
    }
    '/(authenticated)/jds/$id': {
      id: '/(authenticated)/jds/$id'
      path: '/jds/$id'
      fullPath: '/jds/$id'
      preLoaderRoute: typeof authenticatedJdsIdRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/class/$slug': {
      id: '/(authenticated)/class/$slug'
      path: '/class/$slug'
      fullPath: '/class/$slug'
      preLoaderRoute: typeof authenticatedClassSlugRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/backend/settings': {
      id: '/(authenticated)/backend/settings'
      path: '/settings'
      fullPath: '/backend/settings'
      preLoaderRoute: typeof authenticatedBackendSettingsRouteImport
      parentRoute: typeof authenticatedBackendRouteRoute
    }
    '/(authenticated)/backend/fit': {
      id: '/(authenticated)/backend/fit'
      path: '/fit'
      fullPath: '/backend/fit'
      preLoaderRoute: typeof authenticatedBackendFitRouteImport
      parentRoute: typeof authenticatedBackendRouteRoute
    }
    '/(authenticated)/backend/corpus': {
      id: '/(authenticated)/backend/corpus'
      path: '/corpus'
      fullPath: '/backend/corpus'
      preLoaderRoute: typeof authenticatedBackendCorpusRouteImport
      parentRoute: typeof authenticatedBackendRouteRoute
    }
    '/(authenticated)/backend/analytics': {
      id: '/(authenticated)/backend/analytics'
      path: '/analytics'
      fullPath: '/backend/analytics'
      preLoaderRoute: typeof authenticatedBackendAnalyticsRouteImport
      parentRoute: typeof authenticatedBackendRouteRoute
    }
    '/(authenticated)/class/$slug/build': {
      id: '/(authenticated)/class/$slug/build'
      path: '/build'
      fullPath: '/class/$slug/build'
      preLoaderRoute: typeof authenticatedClassSlugBuildRouteImport
      parentRoute: typeof authenticatedClassSlugRoute
    }
    '/(authenticated)/backend/standard/$slug': {
      id: '/(authenticated)/backend/standard/$slug'
      path: '/standard/$slug'
      fullPath: '/backend/standard/$slug'
      preLoaderRoute: typeof authenticatedBackendStandardSlugRouteImport
      parentRoute: typeof authenticatedBackendRouteRoute
    }
    '/(authenticated)/backend/jds/$slug': {
      id: '/(authenticated)/backend/jds/$slug'
      path: '/jds/$slug'
      fullPath: '/backend/jds/$slug'
      preLoaderRoute: typeof authenticatedBackendJdsSlugRouteImport
      parentRoute: typeof authenticatedBackendRouteRoute
    }
    '/(authenticated)/backend/edit/$slug': {
      id: '/(authenticated)/backend/edit/$slug'
      path: '/edit/$slug'
      fullPath: '/backend/edit/$slug'
      preLoaderRoute: typeof authenticatedBackendEditSlugRouteImport
      parentRoute: typeof authenticatedBackendRouteRoute
    }
    '/(authenticated)/backend/jd/$slug/$': {
      id: '/(authenticated)/backend/jd/$slug/$'
      path: '/jd/$slug/$'
      fullPath: '/backend/jd/$slug/$'
      preLoaderRoute: typeof authenticatedBackendJdSlugSplatRouteImport
      parentRoute: typeof authenticatedBackendRouteRoute
    }
  }
}

interface authenticatedBackendRouteRouteChildren {
  authenticatedBackendAnalyticsRoute: typeof authenticatedBackendAnalyticsRoute
  authenticatedBackendCorpusRoute: typeof authenticatedBackendCorpusRoute
  authenticatedBackendFitRoute: typeof authenticatedBackendFitRoute
  authenticatedBackendSettingsRoute: typeof authenticatedBackendSettingsRoute
  authenticatedBackendIndexRoute: typeof authenticatedBackendIndexRoute
  authenticatedBackendEditSlugRoute: typeof authenticatedBackendEditSlugRoute
  authenticatedBackendJdsSlugRoute: typeof authenticatedBackendJdsSlugRoute
  authenticatedBackendStandardSlugRoute: typeof authenticatedBackendStandardSlugRoute
  authenticatedBackendJdSlugSplatRoute: typeof authenticatedBackendJdSlugSplatRoute
}

const authenticatedBackendRouteRouteChildren: authenticatedBackendRouteRouteChildren =
  {
    authenticatedBackendAnalyticsRoute: authenticatedBackendAnalyticsRoute,
    authenticatedBackendCorpusRoute: authenticatedBackendCorpusRoute,
    authenticatedBackendFitRoute: authenticatedBackendFitRoute,
    authenticatedBackendSettingsRoute: authenticatedBackendSettingsRoute,
    authenticatedBackendIndexRoute: authenticatedBackendIndexRoute,
    authenticatedBackendEditSlugRoute: authenticatedBackendEditSlugRoute,
    authenticatedBackendJdsSlugRoute: authenticatedBackendJdsSlugRoute,
    authenticatedBackendStandardSlugRoute:
      authenticatedBackendStandardSlugRoute,
    authenticatedBackendJdSlugSplatRoute: authenticatedBackendJdSlugSplatRoute,
  }

const authenticatedBackendRouteRouteWithChildren =
  authenticatedBackendRouteRoute._addFileChildren(
    authenticatedBackendRouteRouteChildren,
  )

interface authenticatedClassSlugRouteChildren {
  authenticatedClassSlugBuildRoute: typeof authenticatedClassSlugBuildRoute
}

const authenticatedClassSlugRouteChildren: authenticatedClassSlugRouteChildren =
  {
    authenticatedClassSlugBuildRoute: authenticatedClassSlugBuildRoute,
  }

const authenticatedClassSlugRouteWithChildren =
  authenticatedClassSlugRoute._addFileChildren(
    authenticatedClassSlugRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedBackendRouteRoute: typeof authenticatedBackendRouteRouteWithChildren
  authenticatedClassifyRoute: typeof authenticatedClassifyRoute
  authenticatedIndexRoute: typeof authenticatedIndexRoute
  authenticatedClassSlugRoute: typeof authenticatedClassSlugRouteWithChildren
  authenticatedJdsIdRoute: typeof authenticatedJdsIdRoute
  authenticatedJdsIndexRoute: typeof authenticatedJdsIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedBackendRouteRoute: authenticatedBackendRouteRouteWithChildren,
  authenticatedClassifyRoute: authenticatedClassifyRoute,
  authenticatedIndexRoute: authenticatedIndexRoute,
  authenticatedClassSlugRoute: authenticatedClassSlugRouteWithChildren,
  authenticatedJdsIdRoute: authenticatedJdsIdRoute,
  authenticatedJdsIndexRoute: authenticatedJdsIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
