/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as authenticatedClassifyRouteImport } from './routes/(authenticated)/classify'
import { Route as authenticatedBackendIndexRouteImport } from './routes/(authenticated)/backend/index'
import { Route as authenticatedClassSlugRouteImport } from './routes/(authenticated)/class.$slug'
import { Route as authenticatedBackendFitRouteImport } from './routes/(authenticated)/backend/fit'
import { Route as authenticatedClassSlugBuildRouteImport } from './routes/(authenticated)/class.$slug.build'
import { Route as authenticatedBackendStandardSlugRouteImport } from './routes/(authenticated)/backend/standard.$slug'
import { Route as authenticatedBackendJdsSlugRouteImport } from './routes/(authenticated)/backend/jds.$slug'
import { Route as authenticatedBackendEditSlugRouteImport } from './routes/(authenticated)/backend/edit.$slug'
import { Route as authenticatedBackendJdSlugSplatRouteImport } from './routes/(authenticated)/backend/jd.$slug.$'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedClassifyRoute = authenticatedClassifyRouteImport.update({
  id: '/classify',
  path: '/classify',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedBackendIndexRoute =
  authenticatedBackendIndexRouteImport.update({
    id: '/backend/',
    path: '/backend/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedClassSlugRoute = authenticatedClassSlugRouteImport.update({
  id: '/class/$slug',
  path: '/class/$slug',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedBackendFitRoute = authenticatedBackendFitRouteImport.update({
  id: '/backend/fit',
  path: '/backend/fit',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedClassSlugBuildRoute =
  authenticatedClassSlugBuildRouteImport.update({
    id: '/build',
    path: '/build',
    getParentRoute: () => authenticatedClassSlugRoute,
  } as any)
const authenticatedBackendStandardSlugRoute =
  authenticatedBackendStandardSlugRouteImport.update({
    id: '/backend/standard/$slug',
    path: '/backend/standard/$slug',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedBackendJdsSlugRoute =
  authenticatedBackendJdsSlugRouteImport.update({
    id: '/backend/jds/$slug',
    path: '/backend/jds/$slug',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedBackendEditSlugRoute =
  authenticatedBackendEditSlugRouteImport.update({
    id: '/backend/edit/$slug',
    path: '/backend/edit/$slug',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedBackendJdSlugSplatRoute =
  authenticatedBackendJdSlugSplatRouteImport.update({
    id: '/backend/jd/$slug/$',
    path: '/backend/jd/$slug/$',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/classify': typeof authenticatedClassifyRoute
  '/': typeof authenticatedIndexRoute
  '/backend/fit': typeof authenticatedBackendFitRoute
  '/class/$slug': typeof authenticatedClassSlugRouteWithChildren
  '/backend': typeof authenticatedBackendIndexRoute
  '/backend/edit/$slug': typeof authenticatedBackendEditSlugRoute
  '/backend/jds/$slug': typeof authenticatedBackendJdsSlugRoute
  '/backend/standard/$slug': typeof authenticatedBackendStandardSlugRoute
  '/class/$slug/build': typeof authenticatedClassSlugBuildRoute
  '/backend/jd/$slug/$': typeof authenticatedBackendJdSlugSplatRoute
}
export interface FileRoutesByTo {
  '/classify': typeof authenticatedClassifyRoute
  '/': typeof authenticatedIndexRoute
  '/backend/fit': typeof authenticatedBackendFitRoute
  '/class/$slug': typeof authenticatedClassSlugRouteWithChildren
  '/backend': typeof authenticatedBackendIndexRoute
  '/backend/edit/$slug': typeof authenticatedBackendEditSlugRoute
  '/backend/jds/$slug': typeof authenticatedBackendJdsSlugRoute
  '/backend/standard/$slug': typeof authenticatedBackendStandardSlugRoute
  '/class/$slug/build': typeof authenticatedClassSlugBuildRoute
  '/backend/jd/$slug/$': typeof authenticatedBackendJdSlugSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/classify': typeof authenticatedClassifyRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/(authenticated)/backend/fit': typeof authenticatedBackendFitRoute
  '/(authenticated)/class/$slug': typeof authenticatedClassSlugRouteWithChildren
  '/(authenticated)/backend/': typeof authenticatedBackendIndexRoute
  '/(authenticated)/backend/edit/$slug': typeof authenticatedBackendEditSlugRoute
  '/(authenticated)/backend/jds/$slug': typeof authenticatedBackendJdsSlugRoute
  '/(authenticated)/backend/standard/$slug': typeof authenticatedBackendStandardSlugRoute
  '/(authenticated)/class/$slug/build': typeof authenticatedClassSlugBuildRoute
  '/(authenticated)/backend/jd/$slug/$': typeof authenticatedBackendJdSlugSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/classify'
    | '/'
    | '/backend/fit'
    | '/class/$slug'
    | '/backend'
    | '/backend/edit/$slug'
    | '/backend/jds/$slug'
    | '/backend/standard/$slug'
    | '/class/$slug/build'
    | '/backend/jd/$slug/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/classify'
    | '/'
    | '/backend/fit'
    | '/class/$slug'
    | '/backend'
    | '/backend/edit/$slug'
    | '/backend/jds/$slug'
    | '/backend/standard/$slug'
    | '/class/$slug/build'
    | '/backend/jd/$slug/$'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(authenticated)/classify'
    | '/(authenticated)/'
    | '/(authenticated)/backend/fit'
    | '/(authenticated)/class/$slug'
    | '/(authenticated)/backend/'
    | '/(authenticated)/backend/edit/$slug'
    | '/(authenticated)/backend/jds/$slug'
    | '/(authenticated)/backend/standard/$slug'
    | '/(authenticated)/class/$slug/build'
    | '/(authenticated)/backend/jd/$slug/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/classify': {
      id: '/(authenticated)/classify'
      path: '/classify'
      fullPath: '/classify'
      preLoaderRoute: typeof authenticatedClassifyRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/backend/': {
      id: '/(authenticated)/backend/'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof authenticatedBackendIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/class/$slug': {
      id: '/(authenticated)/class/$slug'
      path: '/class/$slug'
      fullPath: '/class/$slug'
      preLoaderRoute: typeof authenticatedClassSlugRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/backend/fit': {
      id: '/(authenticated)/backend/fit'
      path: '/backend/fit'
      fullPath: '/backend/fit'
      preLoaderRoute: typeof authenticatedBackendFitRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/class/$slug/build': {
      id: '/(authenticated)/class/$slug/build'
      path: '/build'
      fullPath: '/class/$slug/build'
      preLoaderRoute: typeof authenticatedClassSlugBuildRouteImport
      parentRoute: typeof authenticatedClassSlugRoute
    }
    '/(authenticated)/backend/standard/$slug': {
      id: '/(authenticated)/backend/standard/$slug'
      path: '/backend/standard/$slug'
      fullPath: '/backend/standard/$slug'
      preLoaderRoute: typeof authenticatedBackendStandardSlugRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/backend/jds/$slug': {
      id: '/(authenticated)/backend/jds/$slug'
      path: '/backend/jds/$slug'
      fullPath: '/backend/jds/$slug'
      preLoaderRoute: typeof authenticatedBackendJdsSlugRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/backend/edit/$slug': {
      id: '/(authenticated)/backend/edit/$slug'
      path: '/backend/edit/$slug'
      fullPath: '/backend/edit/$slug'
      preLoaderRoute: typeof authenticatedBackendEditSlugRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/backend/jd/$slug/$': {
      id: '/(authenticated)/backend/jd/$slug/$'
      path: '/backend/jd/$slug/$'
      fullPath: '/backend/jd/$slug/$'
      preLoaderRoute: typeof authenticatedBackendJdSlugSplatRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedClassSlugRouteChildren {
  authenticatedClassSlugBuildRoute: typeof authenticatedClassSlugBuildRoute
}

const authenticatedClassSlugRouteChildren: authenticatedClassSlugRouteChildren =
  {
    authenticatedClassSlugBuildRoute: authenticatedClassSlugBuildRoute,
  }

const authenticatedClassSlugRouteWithChildren =
  authenticatedClassSlugRoute._addFileChildren(
    authenticatedClassSlugRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedClassifyRoute: typeof authenticatedClassifyRoute
  authenticatedIndexRoute: typeof authenticatedIndexRoute
  authenticatedBackendFitRoute: typeof authenticatedBackendFitRoute
  authenticatedClassSlugRoute: typeof authenticatedClassSlugRouteWithChildren
  authenticatedBackendIndexRoute: typeof authenticatedBackendIndexRoute
  authenticatedBackendEditSlugRoute: typeof authenticatedBackendEditSlugRoute
  authenticatedBackendJdsSlugRoute: typeof authenticatedBackendJdsSlugRoute
  authenticatedBackendStandardSlugRoute: typeof authenticatedBackendStandardSlugRoute
  authenticatedBackendJdSlugSplatRoute: typeof authenticatedBackendJdSlugSplatRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedClassifyRoute: authenticatedClassifyRoute,
  authenticatedIndexRoute: authenticatedIndexRoute,
  authenticatedBackendFitRoute: authenticatedBackendFitRoute,
  authenticatedClassSlugRoute: authenticatedClassSlugRouteWithChildren,
  authenticatedBackendIndexRoute: authenticatedBackendIndexRoute,
  authenticatedBackendEditSlugRoute: authenticatedBackendEditSlugRoute,
  authenticatedBackendJdsSlugRoute: authenticatedBackendJdsSlugRoute,
  authenticatedBackendStandardSlugRoute: authenticatedBackendStandardSlugRoute,
  authenticatedBackendJdSlugSplatRoute: authenticatedBackendJdSlugSplatRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
